apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: model-on-demand
  annotations:
    version: v0.1.0
    description: "Model on demand"
    # experimental: true
spec:
  components:
    - name: api
      type: component
      properties:
        image: file:///home/finnfalter/git/wamli/poc-custom-wit-interface/actors/api/build/api_s.wasm
        id: api
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: fakeml
            namespace: wamli
            package: ml
            interfaces: [inference]
        - type: link
          properties:
            target: preprocessor
            namespace: wamli
            package: ml
            interfaces: [conversion]
    - name: preprocessor
      type: component
      properties:
        image: file:///home/finnfalter/git/wamli/poc-custom-wit-interface/actors/preprocessor/build/preprocessor_s.wasm
        id: preprocessor
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: httpserver
      type: capability
      properties:
        image: localhost:5000/v2/http-server:0.21.0
      traits: 
        - type: link
          properties: 
            target: api
            namespace: wasi
            package: http
            interfaces: [incoming-handler] 
            source_config: 
              - name: default-http
                properties: 
                  ADDRESS: 127.0.0.1:8081

    - name: fakeml
      type: capability
      properties:
        image: localhost:5000/v2/fakeml:0.1.0
        id: fakeml
        config:
          - name: registry-url
            properties:
              url: localhost:5000
