apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ml-inference
  annotations:
    version: v0.1.0
    description: "Machine learning inference"
    # experimental: true
spec:
  components:
    - name: api
      type: component
      properties:
        image: file://components/api/build/api_s.wasm
        id: api
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: inference
            namespace: wamli
            package: ml
            interfaces: [inference]
        - type: link
          properties:
            name: imagenetpreprocessor
            target: imagenetpreprocessor
            namespace: wamli
            package: ml
            interfaces: [conversion]
        - type: link
          properties:
            name: imagenetpostprocessor
            target: imagenetpostprocessor
            namespace: wamli
            package: ml
            interfaces: [classification]
    
    - name: imagenetpreprocessor
      type: component
      properties:
        image: file://components/imagenetpreprocessor/build/imagenetpreprocessor_s.wasm
        id: imagenetpreprocessor
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: imagenetpostprocessor
      type: component
      properties:
        image: file://components/imagenetpostprocessor/build/imagenetpostprocessor_s.wasm
        id: imagenetpostprocessor
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: httpserver
      type: capability
      properties:
        image: localhost:5000/v2/http-server:0.21.0
      traits: 
        - type: link
          properties: 
            target: api
            namespace: wasi
            package: http
            interfaces: [incoming-handler] 
            source_config: 
              - name: default-http
                properties: 
                  ADDRESS: 127.0.0.1:8081

    - name: inference
      type: capability
      properties:
        image: file://providers/inference/build/inference.par.gz
        # image: localhost:5000/v2/inference:0.1.0
        id: inference
        config:
          - name: registry-url
            properties:
              # URL of OCI image registry where to fech model and metadata from
              url: localhost:5000
              mobilenetv27: wamli-mobilenetv27:latest
