[package]
name = "api"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
http = "1.1.0"
serde_json = "1.0"
urlencoding = "2.1.3"
serde = {version = "1.0", features = ["derive"]}
wit-bindgen = { version = "0.24", features = ["default"] }
