package wamli:mlinference;

world api {
  import wasmcloud:bus/lattice@1.0.0;
  import wasi:logging/logging;
  import wamli:ml/inference;
  import wamli:ml/conversion;
  import wamli:ml/classification;

  export wasi:http/incoming-handler@0.2.0;
}

